### ISSUE TITLE
Extract Publickey handler from Certificate

### ISSUE THREAD

**Issue by mahdiit** [Pkcs11Interop/Pkcs11Interop#142]
hi
i have a problem, my token (hardware) contain PrivateKey and One Certificate
all example for rsa encrypt and decrypt use  private and public key
how can i use certificate public key as publickey handler for Encrypt process ?
and use in Encrypt method ??? 

https://github.com/Pkcs11Interop/Pkcs11Interop/blob/5.0.0/src/Pkcs11Interop.Tests/HighLevelAPI/_19_EncryptAndDecryptTest.cs

**Comment by mahdiit** [comment]
i one found answer, i must use bouncy castle methods

```
X509CertificateParser parser = new X509CertificateParser();
            var x509Cert = parser.ReadCertificate(certificate.CkaValue);
            var publicKeyInfo = SubjectPublicKeyInfoFactory.CreateSubjectPublicKeyInfo(x509Cert.GetPublicKey());
            var result = publicKeyInfo.ToAsn1Object().GetDerEncoded();
            RsaKeyParameters publicKey = (RsaKeyParameters)PublicKeyFactory.CreateKey(result);

            // PKCS1 v1.5 paddings
            Pkcs1Encoding eng = new Pkcs1Encoding(new RsaEngine());
            eng.Init(true, publicKey);

            return eng.ProcessBlock(data,0,data.Length);
```

**Comment by qpernil** [comment]
If the question is how can you use the C_Encrypt PKCS#11 method with a certificate object the short answer is that you can't. But some PKCS#11 implementations may expose the public key from the certificate as a public key object as well, and then you could use that object handle with C_Encrypt. Typically the PKCS#11 module would then perform the public key operation in software (which is fine, since it's a public key).
