### ISSUE TITLE
safe pin entry doesnt work for C#?

### ISSUE THREAD

**Issue by mgebros** [Pkcs11Interop/Pkcs11Interop#149]
![image](https://user-images.githubusercontent.com/47592547/76953845-d3213a80-6928-11ea-805c-ee8ba482aaee.png)

As you suggested I already wrote a question to the vendor of the pkcs11-geo-eid-x64.dll library.

However I forgot to notice very important thing: Same library works totally fine for the Java program for years.
![image](https://user-images.githubusercontent.com/47592547/76954078-33b07780-6929-11ea-8cc9-d977897331cd.png)
As you can see it recognizes the device and in case I click the button of PIN entry the it asks to enter the pin etc. (the flow works).
When I looked the decompiled Java files that program doesn't contain any specific different methods then PKCS11Interop has. That program ask to enter empty string for safe pin entry but it works. 

So is the problem with C# programming language?

**Comment by jariq** [comment]
> So is the problem with C# programming language?

I don't think it is but if you want to dig more into the problem here's what you can do while you wait for the response from PKCS#11 librayr vendor:

1. Log all PKCS#11 calls of JAVA program with [PKCS11-LOGGER](https://github.com/Pkcs11Interop/pkcs11-logger)
2. Log all PKCS#11 calls of your C# program with [PKCS11-LOGGER](https://github.com/Pkcs11Interop/pkcs11-logger)
3. Compare captured logs and try to find the difference

**Comment by jariq** [comment]
Another thing that comes to my mind is that you should also check that both apps use the same version of unmanaged PKCS#11 library. I've seen libraries where 64-bit and 32-bit versions had different behavior.

**Comment by jariq** [comment]
Closing because of 14+ days without a response.
