### ISSUE TITLE
Get the counter of the PIN retries

### ISSUE THREAD

**Issue by Albvadi** [Pkcs11Interop/Pkcs11Interop#157]
Pkcs11Interop: **v5.1.0**
S.O: **Windows 10**
SmartCard Provider: **G&D Sm@rtCafe 5.x**
Library: **aetpkss1.dll**

Hi,
first of all, thanks for these amazing ecosystem (Pkcs11Interop, Pkcs11Admin, etc...), it would be very frustrating and difficult to develop something without all the help of these projects.

I´m trying to get the counter of the PIN/PUK retries. My card provider has the option with the dll and his software, but with Pkcs11Interop I don´t see the methods to get the counter.

![image](https://user-images.githubusercontent.com/6285255/86113412-858ca000-bac9-11ea-8560-147bd579b2a0.png)

There are any way to get the counter?

If there is no way to get the counter and the max retries are always the same (3, but I´m not sure if it´s always same or can be changed), maybe playing with the status properties I could get the counter in the way:
- **3 retries**
  - User PIN count low = **false**
- **2 retries:**
  - User PIN count low = **true**
  - User PIN final try = **false**
- **1 and last try**
  - User PIN count low = **true**
  - User PIN final try = **true**

Thanks!

**Comment by jariq** [comment]
I highly doubt that `2/3` information on your screenshot was acquired via standard PKCS#11 API because standard PKCS#11 API does not provide any means to read the number of authentication retries etc. All it provides are those flags that you already found. And yes most of the cards I've seen allows those numbers to be customized (not via PKCS#11 API though) so your best bet is to contact device vendor and ask for more information on how to read those numbers.
