### ISSUE TITLE
Error in GetValueAsBool 

### ISSUE THREAD

**Issue by mahdiit** [Pkcs11Interop/Pkcs11Interop#38]
hi
i have old source of pkcs11 lib, that read my token 
today i updated to least version and get error in ReadCertificate method, i debug it and found an inner method in ObjectAttribute.cs in HightLevelApi 

```
public bool GetValueAsBool()
        {
            if (this._disposed)
                throw new ObjectDisposedException(this.GetType().FullName);

            if (Platform.UnmanagedLongSize == 4)
                return (Platform.StructPackingSize == 0) ? _objectAttribute40.GetValueAsBool() : _objectAttribute41.GetValueAsBool();
            else
                return (Platform.StructPackingSize == 0) ? _objectAttribute80.GetValueAsBool() : _objectAttribute81.GetValueAsBool();
        }
```
that throw error: `Unable to convert byte to bool`

but my old source that work and read certificate:
```
public bool GetValueAsBool()
        {
            if (this._disposed)
                throw new ObjectDisposedException(this.GetType().FullName);

            if (UnmanagedLong.Size == 4)
                return _objectAttribute4.GetValueAsBool();
            else
                return _objectAttribute8.GetValueAsBool();
        }
```

![image 2 2](https://cloud.githubusercontent.com/assets/67848/21309838/1cd70b58-c5f5-11e6-9b5a-6a8b6cc5ebd4.png)

Update: 
i found that  this method throw eception: `public static bool BytesToBool(byte[] value)`
in file .\Common\ConvertUtils.cs

i fixed with these codes: 
```
public static bool BytesToBool(byte[] value)
        {
            // Cryptoki uses boolean flag with size of 1 byte
            if ((value == null) || (value.Length != 1))
                value = new byte[] {0};
            
            return BitConverter.ToBoolean(value, 0);
        }
```
Problem solved. please fix in your source

**Comment by jariq** [comment]
Your application seems to be reading the value of some attribute which is expected to have a `bool` value. In PKCS#11 `bool` values are represented with `CK_BBOOL` type which is exactly 1 byte long. Skipping the check for correct length of attribute value may hide serious bugs in unmanaged PKCS#11 libraries.

Please provide the answer for following questions:
1. Which attribute is causing the problem?
2. What is the value of attribute? Is it null or is its length other than 1?
3. Did you check `CannotBeRead` member of `ObjectAttribute ` class before using attribute value?

It would be great if you could [use PKCS11-LOGGER to troubleshoot your issue](https://github.com/Pkcs11Interop/Pkcs11Interop/blob/3.2.0/doc/TROUBLESHOOTING.md) and send me the logs.

**Comment by mahdiit** [comment]
ok, i test,  i am using pkcs11-logger and library speed increased!!!! i do not know why
also i have some exception that there is not exist any more (i think some thing need logger)

i will test and report result about this issue

**Comment by mahdiit** [comment]
[pkcs11-logger-x64.zip](https://github.com/Pkcs11Interop/Pkcs11Interop/files/672097/pkcs11-logger-x64.zip)
this is log file when using this method and it throw exception
![image 1](https://cloud.githubusercontent.com/assets/67848/21470112/7d91cd9a-ca8f-11e6-867d-173cc33e271c.jpg)

**Comment by jariq** [comment]
You seem to be using [Pkcs11Admin](http://pkcs11admin.net/) application which in its current version [requires 5 attributes](https://github.com/Pkcs11Admin/Pkcs11Admin/blob/0.3.0/src/Pkcs11Admin/Pkcs11Slot.cs#L509) to be readable on certificate object. However your logs show that unmanaged PKCS#11 library provided by Longmai considers `CKA_PRIVATE` attribute on certificate object to be an invalid attribute because it returns `CKR_ATTRIBUTE_TYPE_INVALID` code when those 5 attributes are being read and marks the value of `CKA_PRIVATE` attribute as the one that cannot be read:

	0x00000828 : 0x00000384 : ****************************** 1395-10-05 10:32:41 ***
	0x00000828 : 0x00000384 : Calling C_GetAttributeValue
	0x00000828 : 0x00000384 : Input
	0x00000828 : 0x00000384 :  hSession: 621484320
	0x00000828 : 0x00000384 :  hObject: 621483648
	0x00000828 : 0x00000384 :  pTemplate: 0000020F242F9A10
	0x00000828 : 0x00000384 :  ulCount: 5
	0x00000828 : 0x00000384 :   *** Begin attribute template ***
	0x00000828 : 0x00000384 :   Attribute 0
	0x00000828 : 0x00000384 :    Attribute: 2 (CKA_PRIVATE)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 0
	0x00000828 : 0x00000384 :   Attribute 1
	0x00000828 : 0x00000384 :    Attribute: 128 (CKA_CERTIFICATE_TYPE)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 0
	0x00000828 : 0x00000384 :   Attribute 2
	0x00000828 : 0x00000384 :    Attribute: 3 (CKA_LABEL)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 0
	0x00000828 : 0x00000384 :   Attribute 3
	0x00000828 : 0x00000384 :    Attribute: 258 (CKA_ID)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 0
	0x00000828 : 0x00000384 :   Attribute 4
	0x00000828 : 0x00000384 :    Attribute: 17 (CKA_VALUE)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 0
	0x00000828 : 0x00000384 :   *** End attribute template ***
	0x00000828 : 0x00000384 : Output
	0x00000828 : 0x00000384 :  pTemplate: 0000020F242F9A10
	0x00000828 : 0x00000384 :  ulCount: 5
	0x00000828 : 0x00000384 :   *** Begin attribute template ***
	0x00000828 : 0x00000384 :   Attribute 0
	0x00000828 : 0x00000384 :    Attribute: 2 (CKA_PRIVATE)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 4294967295
	0x00000828 : 0x00000384 :   Attribute 1
	0x00000828 : 0x00000384 :    Attribute: 128 (CKA_CERTIFICATE_TYPE)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 4
	0x00000828 : 0x00000384 :   Attribute 2
	0x00000828 : 0x00000384 :    Attribute: 3 (CKA_LABEL)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 10
	0x00000828 : 0x00000384 :   Attribute 3
	0x00000828 : 0x00000384 :    Attribute: 258 (CKA_ID)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 10
	0x00000828 : 0x00000384 :   Attribute 4
	0x00000828 : 0x00000384 :    Attribute: 17 (CKA_VALUE)
	0x00000828 : 0x00000384 :    pValue: 0000000000000000
	0x00000828 : 0x00000384 :    ulValueLen: 1224
	0x00000828 : 0x00000384 :   *** End attribute template ***
	0x00000828 : 0x00000384 : Returning 18 (CKR_ATTRIBUTE_TYPE_INVALID)

Both unmanaged PKCS#11 library and Pkcs11Admin application are responsible for this incompatibility so let's summarize the facts:

- [PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/raw/master/v2.20/pkcs-11v2-20.pdf) states in chapter 10.4 that `CKA_PRIVATE` attribute is valid for all storage objects and figure 5 in chapter 10 definitely shows that certificate is storage object.
- However unmanaged PKCS#11 library does not consider `CKA_PRIVATE` attribute to be valid and marks the attribute as such by setting the ulValueLen field to hold the value -1 (4294967295).
- Pkcs11Admin foolishly expects `CKA_PRIVATE` attribute of the certificate object to be readable and does not check if it really is. That's why you are getting "Unable to convert bytes to bool" exception.

I will most likely modify Pkcs11Admin to no longer assume that some attributes are essential and always readable because this case clearly shows they are not. Regardless of that I believe that Longmai should fix handling of `CKA_PRIVATE` attribute in their library which BTW also incorrectly encodes the value of `CKA_SERIAL_NUMBER` attribute. I'll notify Longmai engineers about this thread via LinkedIn.

Meanwhile it would be great if you could change [line 535 in Pkcs11Slot.cs](https://github.com/Pkcs11Admin/Pkcs11Admin/blob/0.3.0/src/Pkcs11Admin/Pkcs11Slot.cs#L535) from

    CkaPrivate = requiredAttributes[0].GetValueAsBool(),

to

    CkaPrivate = (requiredAttributes[0].CannotBeRead) ? false : requiredAttributes[0].GetValueAsBool(),

and report back with the results.

**Comment by mahdiit** [comment]
yes Pkcs11Admin is some part of my codes, there are three certificate in token and only one of them has CKA_PRIVATE attribute and when reading this section in throw exception.

i fix it with codes that you provided.

**Comment by jariq** [comment]
@mahdiit did suggested code change fixed the issue for you?

**Comment by mahdiit** [comment]
sorry for long time response, i am busy and testing, so yes this fix problem but i found i must test this for every property because can cause problem in my application.
thanks
