### ISSUE TITLE
Invalid Characters in Token Data

### ISSUE THREAD

**Issue by mahdiit** [Pkcs11Interop/Pkcs11Interop#39]
hi
i read hardware token in pkcs11 lib but when display data i see that there is some character in token title
![image 4](https://cloud.githubusercontent.com/assets/67848/21311276/99838248-c5fb-11e6-84aa-b23c805f9810.jpg)

i think that middle ware of token generate zero byte as empty so, i replace some codes to show token label correctly

`info = pkcs11Slot.TokenInfo.Label.SafeReplace("\0",string.Empty),
`
i test with another brand of token and these error does not exist.
i found that token with brand "[mToken K3](http://www.longmai.net/products/mtoken/longmai-autoken-2fa/)" has this problem, i think better there is way to show only human readable characters, but i do not know howto do this

**Comment by jariq** [comment]
[PKCS#11 v2.20 specification](https://github.com/Pkcs11Interop/PKCS11-SPECS/raw/master/v2.20/pkcs-11v2-20.pdf) states in chapter 9.2 that `label` member of `CK_TOKEN_INFO` structure is:

> application-defined label, assigned during token initialization. **Must be padded with the blank character
> (‘ ‘). Should not be null-terminated.**

IMO there are two possible explanations for your problem:

1. Unmanaged PKCS#11 library you are using is violating the specification by padding the label with '\0' characters instead of spaces; or
2. application you have used for token initialization incorrectly padded the label with '\0' characters instead of spaces.

I don't think it is a good idea to introduce workarounds for this problem in Pkcs11Interop. It needs to be fixed in unmanaged PKCS#11 library or in application performing token initialization.

**Comment by mahdiit** [comment]
yes, your are true, i test and see error was in middle ware of token, report to issuer company
