### ISSUE TITLE
Exception when disposing Session AFTER parent Pkcs11

### ISSUE THREAD

**Issue by Timovzl** [Pkcs11Interop/Pkcs11Interop#64]
I have a situation where the Pkcs11 instance is disposed _before_ the Session instance. This is because the Pkcs11 is managed at a higher level, where different factors can cause it to be disposed, factors that the Session level may not know about.

Eventually, the Session-managing level finds out, and it disposes the now unusable Session object. **The Session object tries to call C_CloseSession() on its parent Pkcs11, but that throws an ObjectDisposedException().**

This prevents us from doing a proper cleanup.

Of course, being unable to do cryptographic operations on the Session object in this situation is perfectly correct. But **cleaning up should always be possible**.

Here are two suggested solutions:

- **Have the Pkcs11 instance (also) call its own C_CloseSession() when disposing**, instead of making this solely the responsibility of the Session object. As it stands, part of the Pkcs11 object stays intact when it is disposed, i.e. it currently does not seem to be taking proper responsibility for its own cleanup.
- Allow the C_CloseSession() to be called even when the Pkcs11 is already disposed, as it is a cleanup method. This sounds fine in theory, but may be infeasible in practice, as it may still require the (now unloaded) DLL.

**Comment by jariq** [comment]
> Session object tries to call C_CloseSession() on its parent Pkcs11, but that throws an ObjectDisposedException().

And that is a correct and expected behavior. This should be the sign for you that you are using Pkcs11Interop library incorrectly and that you are disposing `Pkcs11` and `Session` instances in an incorrect order.

My suggestion is that you rewrite your code so you never dispose `Pkcs11` instance before other PKCS#11 related objects such as `Session` instances are "alive".

**Comment by Timovzl** [comment]
While that is the most obvious order of disposal, is it necessary or beneficial to enforce it?

For context, I am using Utimaco HSMs. Utimaco uses a config file to determine which device to access. I need to access two devices, for manual failover. If I use the interop library to load Utimaco's P11 DLL twice, each time with a different config file, then _both_ behave as if they were loaded with the _first_ config file. Presumably something is being cached somewhere. The only approach that seems to work, in order to switch devices, is to dispose the existing Pkcs11, output a new config file, and then instantiate a new Pkcs11.

The above makes it necessary to manage the Pkcs11 instance on a high, application-wide level (mutex + failover). The sessions, on the other hand, are context-specific and therefore slot-specific, so they must be managed from within their respective contexts.

If one session requires a failover, disposing the Pkcs11 instance so that a new one can be created, other contexts become aware of this when they see the new instance, which is their trigger to dispose their sessions and open new ones.

What I'm trying to illustrate is that Pkcs11 inevitably makes us dependent on the vendor's restrictions. That becomes problematic if the interop library is restrictive also.

I hope I have described the situation adequately. So from this perspective, I would repeat my question: is the limitation necessary or beneficial?

**Comment by jariq** [comment]
> For context, I am using Utimaco HSMs. Utimaco uses a config file to determine which device to access. I need to access two devices, for manual failover. If I use the interop library to load Utimaco's P11 DLL twice, each time with a different config file, then both behave as if they were loaded with the first config file. Presumably something is being cached somewhere. The only approach that seems to work, in order to switch devices, is to dispose the existing Pkcs11, output a new config file, and then instantiate a new Pkcs11.

IMO that is expected behavior. [PKCS#11 v2.20][1] chapter 6.6 indicates that from application perspective PKCS#11 library initialization and finalization are global events so IMO single library cannot be loaded and initialized more than once in different contexts (with different settings).

BTW do you know that PKCS#11 library from Utimaco allows you to specify more than one device in configuration file for automatic failover?

> If one session requires a failover, disposing the Pkcs11 instance so that a new one can be created, other contexts become aware of this when they see the new instance, which is their trigger to dispose their sessions and open new ones.

I see your pain but disposing session quietly as you are suggesting just doesn't feel right to me. It is like trying to quietly end database transaction after the database connection has been closed. 


> I hope I have described the situation adequately. So from this perspective, I would repeat my question: is the limitation necessary or beneficial?

Yes, IMO it is. Pkcs11Interop follows ANSI C API defined in PKCS#11 specification as closely as possible so everything written in ANSI C specification is also true for C# wrapper and anyone familiar with PKCS#11 specification knows how to use Pkcs11Interop.

I have thought about this a lot and my original suggestion (that you should rewrite your code so you never dispose `Pkcs11` instance before other PKCS#11 related objects such as `Session` instances are "alive") still stands.

But I also understand that you might not agree with me or might not be willing to do the rewrite so I have second alternative suggestion for you:

When you look at the [implementation of `Dispose` method of `Session` class][2] you will see that it does nothing else than just closes the session. If you believe that `Session` instance should be disposed with already disposed `Pkcs11` instance without any exception then you can just "swallow" `ObjectDisposedException` thrown from the `Dispose` method of `Session` object. I'm not saying it is the best thing to do but I've seen [some people create extension methods doing similar things][3] so this might be a common solution for similar problems.






[1]: https://github.com/Pkcs11Interop/PKCS11-SPECS/tree/master/v2.20
[2]: https://github.com/Pkcs11Interop/Pkcs11Interop/blob/4.0.0/src/Pkcs11Interop/Pkcs11Interop/HighLevelAPI41/Session.cs#L2389-L2403
[3]: https://github.com/JasperFx/baseline/blob/master/src/Baseline/DisposableExtensions.cs#L12-L22

**Comment by Timovzl** [comment]
Thank you for your additional suggestions. They are very welcome.

> BTW do you know that PKCS#11 library from Utimaco allows you to specify more than one device in configuration file for automatic failover?

You're awfully well-informed! We found that this behavior is not documented well enough that we to rely on it. With extensive testing, though, it might turn out to be a suitable alternative.

For now I will settle on a pre-disposal event in my Pkcs11-managing class, so that any Session-managing classes can get rid of their Session objects in a timely manner.

I appreciate the detailed response!

Out of curiosity: Does the enforced order of disposal fulfill a technical requirement? Does closing the session happen to use the DLL? I mean, the order of disposal is definitely not a "feature" that anyone might "miss" if it were no longer obligatory... But if access to the DLL is required to close the session, it all makes a lot more sense.

**Comment by jariq** [comment]
> Does closing the session happen to use the DLL?

Yes exactly. To close the session one need to call `C_CloseSession` function exported by unmanaged PKCS#11 library.
